// ============================================
// GAME CONSTANTS
// ============================================

export const GRID_SIZE = 24;
export const CELL_SIZE = 28;

// ============================================
// ROOM TYPES
// ============================================

export const ROOM_TYPES = {
  cockpit: {
    id: 'cockpit',
    name: 'Cockpit',
    icon: '🎯',
    color: '#3b82f6',
    minCells: 4,
    maxCells: 6,
    basePower: -2,
    baseCrewSlots: 2,
    description: 'Ship control center. Required for piloting.',
    category: 'essential',
    availableSystems: ['navigation-console', 'sensor-terminal', 'autopilot', 'combat-computer'],
  },
  crew: {
    id: 'crew',
    name: 'Crew Quarters',
    icon: '🛏️',
    color: '#22c55e',
    minCells: 4,
    maxCells: 12,
    basePower: -1,
    baseCrewSlots: 4,
    crewPerCell: 0.5, // +1 crew capacity per 2 cells
    description: 'Living space for crew. Determines max crew.',
    category: 'essential',
    availableSystems: ['life-support', 'recreation-unit', 'mess-hall'],
  },
  cargo: {
    id: 'cargo',
    name: 'Cargo Bay',
    icon: '📦',
    color: '#eab308',
    minCells: 4,
    maxCells: 20,
    basePower: -1,
    baseCrewSlots: 1,
    cargoPerCell: 50,
    description: 'Storage for goods and resources.',
    category: 'utility',
    availableSystems: ['cargo-crane', 'refrigeration', 'hazmat-containment'],
  },
  engine: {
    id: 'engine',
    name: 'Engine Room',
    icon: '🔥',
    color: '#f97316',
    minCells: 4,
    maxCells: 12,
    basePower: 0,
    baseCrewSlots: 2,
    description: 'Propulsion systems. Required for movement.',
    category: 'essential',
    availableSystems: ['basic-thruster', 'ion-drive', 'fusion-engine', 'jump-drive', 'afterburner', 'fuel-injector'],
  },
  reactor: {
    id: 'reactor',
    name: 'Reactor Core',
    icon: '⚛️',
    color: '#06b6d4',
    minCells: 4,
    maxCells: 9,
    basePower: 0, // Reactors generate power via systems
    baseCrewSlots: 2,
    description: 'Power generation. Supplies all systems.',
    category: 'essential',
    availableSystems: ['basic-reactor', 'fusion-reactor', 'antimatter-core', 'backup-capacitor', 'coolant-system'],
  },
  weapons: {
    id: 'weapons',
    name: 'Weapons Bay',
    icon: '🔫',
    color: '#ef4444',
    minCells: 4,
    maxCells: 12,
    basePower: -4,
    baseCrewSlots: 2,
    weaponMountsPerCells: 3, // +1 weapon mount per 3 cells
    description: 'Weapon systems and ammunition.',
    category: 'combat',
    availableSystems: ['pulse-cannon', 'railgun', 'missile-rack', 'beam-turret', 'point-defense', 'torpedo-launcher', 'ammo-feed'],
  },
  shields: {
    id: 'shields',
    name: 'Shield Generator',
    icon: '🛡️',
    color: '#8b5cf6',
    minCells: 4,
    maxCells: 9,
    basePower: -5,
    baseCrewSlots: 1,
    description: 'Defensive shield systems.',
    category: 'combat',
    availableSystems: ['shield-emitter', 'advanced-emitter', 'shield-capacitor', 'hardened-shields'],
  },
  medbay: {
    id: 'medbay',
    name: 'Medical Bay',
    icon: '💊',
    color: '#ec4899',
    minCells: 4,
    maxCells: 9,
    basePower: -2,
    baseCrewSlots: 1,
    description: 'Crew healing and cloning.',
    category: 'support',
    availableSystems: ['med-station', 'surgery-suite', 'cloning-pod', 'quarantine-cell'],
  },
  mining: {
    id: 'mining',
    name: 'Mining Bay',
    icon: '⛏️',
    color: '#a855f7',
    minCells: 6,
    maxCells: 16,
    basePower: -4,
    baseCrewSlots: 3,
    miningBonusPerCell: 0.125, // +12.5% per cell above minimum
    description: 'Resource extraction equipment.',
    category: 'industry',
    availableSystems: ['mining-laser', 'heavy-mining-laser', 'ore-processor', 'tractor-beam', 'deep-core-drill'],
  },
  hangar: {
    id: 'hangar',
    name: 'Fighter Hangar',
    icon: '✈️',
    color: '#64748b',
    minCells: 9,
    maxCells: 25,
    basePower: -3,
    baseCrewSlots: 4,
    fightersPerCells: 4, // +1 fighter per 4 cells
    description: 'Fighter storage and deployment.',
    category: 'combat',
    availableSystems: ['launch-tube', 'repair-arm', 'fighter-rack', 'pilot-ready-room'],
  },
  research: {
    id: 'research',
    name: 'Research Lab',
    icon: '🔬',
    color: '#14b8a6',
    minCells: 4,
    maxCells: 12,
    basePower: -3,
    baseCrewSlots: 2,
    description: 'Technology research.',
    category: 'support',
    availableSystems: ['research-terminal', 'prototype-fab', 'data-archive'],
  },
  sensors: {
    id: 'sensors',
    name: 'Sensor Array',
    icon: '📡',
    color: '#38bdf8',
    minCells: 4,
    maxCells: 6,
    basePower: -2,
    baseCrewSlots: 1,
    description: 'Detection and scanning.',
    category: 'utility',
    availableSystems: ['basic-sensors', 'deep-scanner', 'ecm-suite', 'targeting-computer'],
  },
};

// ============================================
// SYSTEMS (Equipment within rooms)
// ============================================

export const SYSTEMS = {
  // Cockpit systems
  'navigation-console': {
    id: 'navigation-console',
    name: 'Navigation Console',
    roomType: 'cockpit',
    power: -1,
    description: 'Enables piloting',
    effects: { canPilot: true },
    required: true,
  },
  'sensor-terminal': {
    id: 'sensor-terminal',
    name: 'Sensor Terminal',
    roomType: 'cockpit',
    power: -1,
    description: '+25% detection range',
    effects: { sensorRangeBonus: 0.25 },
  },
  'autopilot': {
    id: 'autopilot',
    name: 'Autopilot Module',
    roomType: 'cockpit',
    power: -1,
    description: 'Enables auto-navigation',
    effects: { canAutopilot: true },
  },
  'combat-computer': {
    id: 'combat-computer',
    name: 'Combat Computer',
    roomType: 'cockpit',
    power: -2,
    description: '+10% weapon accuracy',
    effects: { accuracyBonus: 0.1 },
  },

  // Engine systems
  'basic-thruster': {
    id: 'basic-thruster',
    name: 'Basic Thruster',
    roomType: 'engine',
    power: -2,
    description: '100 base speed',
    effects: { speed: 100 },
    tier: 1,
  },
  'ion-drive': {
    id: 'ion-drive',
    name: 'Ion Drive',
    roomType: 'engine',
    power: -3,
    description: '150 base speed, efficient',
    effects: { speed: 150, fuelEfficiency: 0.2 },
    tier: 2,
  },
  'fusion-engine': {
    id: 'fusion-engine',
    name: 'Fusion Engine',
    roomType: 'engine',
    power: -5,
    description: '250 base speed',
    effects: { speed: 250 },
    tier: 3,
  },
  'jump-drive': {
    id: 'jump-drive',
    name: 'Jump Drive',
    roomType: 'engine',
    power: -8,
    description: 'Enables inter-system travel',
    effects: { canJump: true },
    tier: 3,
  },
  'afterburner': {
    id: 'afterburner',
    name: 'Afterburner',
    roomType: 'engine',
    power: -2,
    description: '+50% speed burst (cooldown)',
    effects: { afterburnerBonus: 0.5, afterburnerCooldown: 30 },
  },
  'fuel-injector': {
    id: 'fuel-injector',
    name: 'Fuel Injector',
    roomType: 'engine',
    power: -1,
    description: '+25% fuel efficiency',
    effects: { fuelEfficiency: 0.25 },
  },

  // Reactor systems
  'basic-reactor': {
    id: 'basic-reactor',
    name: 'Basic Reactor',
    roomType: 'reactor',
    power: 10,
    description: '+10 power output',
    effects: {},
    tier: 1,
  },
  'fusion-reactor': {
    id: 'fusion-reactor',
    name: 'Fusion Reactor',
    roomType: 'reactor',
    power: 18,
    description: '+18 power output',
    effects: {},
    tier: 2,
  },
  'antimatter-core': {
    id: 'antimatter-core',
    name: 'Antimatter Core',
    roomType: 'reactor',
    power: 35,
    description: '+35 power output, volatile',
    effects: { explosionRisk: 0.1 },
    tier: 3,
  },
  'backup-capacitor': {
    id: 'backup-capacitor',
    name: 'Backup Capacitor',
    roomType: 'reactor',
    power: 0,
    description: '30 second emergency power',
    effects: { emergencyPowerDuration: 30 },
  },
  'coolant-system': {
    id: 'coolant-system',
    name: 'Coolant System',
    roomType: 'reactor',
    power: -1,
    description: '-20% reactor damage risk',
    effects: { damageResistance: 0.2 },
  },

  // Weapon systems
  'pulse-cannon': {
    id: 'pulse-cannon',
    name: 'Pulse Cannon',
    roomType: 'weapons',
    power: -3,
    description: 'Medium damage, medium range',
    effects: { damage: 25, range: 500, fireRate: 1.0 },
    tier: 1,
  },
  'railgun': {
    id: 'railgun',
    name: 'Railgun',
    roomType: 'weapons',
    power: -4,
    description: 'High damage, long range, slow',
    effects: { damage: 50, range: 800, fireRate: 0.5, armorPiercing: 0.5 },
    tier: 2,
  },
  'missile-rack': {
    id: 'missile-rack',
    name: 'Missile Rack',
    roomType: 'weapons',
    power: -3,
    description: 'High damage, guided, limited ammo',
    effects: { damage: 40, range: 600, fireRate: 0.8, guided: true, ammoCapacity: 20 },
    tier: 2,
  },
  'beam-turret': {
    id: 'beam-turret',
    name: 'Beam Turret',
    roomType: 'weapons',
    power: -5,
    description: 'Sustained damage, shield bonus',
    effects: { damage: 15, range: 400, fireRate: 3.0, shieldDamageBonus: 0.5 },
    tier: 2,
  },
  'point-defense': {
    id: 'point-defense',
    name: 'Point Defense',
    roomType: 'weapons',
    power: -2,
    description: 'Anti-missile, anti-fighter',
    effects: { damage: 10, range: 200, fireRate: 5.0, antiMissile: true, antiFighter: true },
    tier: 1,
  },
  'torpedo-launcher': {
    id: 'torpedo-launcher',
    name: 'Torpedo Launcher',
    roomType: 'weapons',
    power: -6,
    description: 'Very high damage, anti-capital',
    effects: { damage: 100, range: 700, fireRate: 0.2, antiCapital: true, ammoCapacity: 8 },
    tier: 3,
  },
  'ammo-feed': {
    id: 'ammo-feed',
    name: 'Ammo Feed',
    roomType: 'weapons',
    power: 0,
    description: '+50% ammo capacity',
    effects: { ammoCapacityBonus: 0.5 },
  },

  // Shield systems
  'shield-emitter': {
    id: 'shield-emitter',
    name: 'Shield Emitter',
    roomType: 'shields',
    power: -4,
    description: '+100 shield HP',
    effects: { shieldHP: 100, shieldRegen: 5 },
    tier: 1,
  },
  'advanced-emitter': {
    id: 'advanced-emitter',
    name: 'Advanced Emitter',
    roomType: 'shields',
    power: -7,
    description: '+250 shield HP',
    effects: { shieldHP: 250, shieldRegen: 10 },
    tier: 2,
  },
  'shield-capacitor': {
    id: 'shield-capacitor',
    name: 'Shield Capacitor',
    roomType: 'shields',
    power: -2,
    description: '+50% recharge rate',
    effects: { shieldRegenBonus: 0.5 },
  },
  'hardened-shields': {
    id: 'hardened-shields',
    name: 'Hardened Shields',
    roomType: 'shields',
    power: -3,
    description: '+25% resistance',
    effects: { shieldResistance: 0.25 },
  },

  // Mining systems
  'mining-laser': {
    id: 'mining-laser',
    name: 'Mining Laser',
    roomType: 'mining',
    power: -2,
    description: 'Base extraction rate',
    effects: { miningRate: 1.0 },
    tier: 1,
  },
  'heavy-mining-laser': {
    id: 'heavy-mining-laser',
    name: 'Heavy Mining Laser',
    roomType: 'mining',
    power: -4,
    description: '+100% extraction rate',
    effects: { miningRate: 2.0 },
    tier: 2,
  },
  'ore-processor': {
    id: 'ore-processor',
    name: 'Ore Processor',
    roomType: 'mining',
    power: -2,
    description: 'Refines ore (+25% value)',
    effects: { refiningBonus: 0.25 },
  },
  'tractor-beam': {
    id: 'tractor-beam',
    name: 'Tractor Beam',
    roomType: 'mining',
    power: -2,
    description: 'Pulls cargo, asteroids',
    effects: { canTractor: true, tractorRange: 300 },
  },
  'deep-core-drill': {
    id: 'deep-core-drill',
    name: 'Deep Core Drill',
    roomType: 'mining',
    power: -3,
    description: 'Access rare deposits',
    effects: { canMineRare: true },
    tier: 3,
  },

  // Medical systems
  'med-station': {
    id: 'med-station',
    name: 'Med Station',
    roomType: 'medbay',
    power: -1,
    description: 'Heals 1 crew/minute',
    effects: { healRate: 1 },
    tier: 1,
  },
  'surgery-suite': {
    id: 'surgery-suite',
    name: 'Surgery Suite',
    roomType: 'medbay',
    power: -2,
    description: 'Heals critical injuries',
    effects: { canHealCritical: true, healRate: 2 },
    tier: 2,
  },
  'cloning-pod': {
    id: 'cloning-pod',
    name: 'Cloning Pod',
    roomType: 'medbay',
    power: -3,
    description: 'Revives dead crew (slow)',
    effects: { canClone: true, cloneTime: 300 },
    tier: 3,
  },
  'quarantine-cell': {
    id: 'quarantine-cell',
    name: 'Quarantine Cell',
    roomType: 'medbay',
    power: -1,
    description: 'Contains infections',
    effects: { canQuarantine: true },
  },

  // Hangar systems
  'launch-tube': {
    id: 'launch-tube',
    name: 'Launch Tube',
    roomType: 'hangar',
    power: -2,
    description: 'Deploy 1 fighter/30s',
    effects: { launchRate: 2 }, // fighters per minute
  },
  'repair-arm': {
    id: 'repair-arm',
    name: 'Repair Arm',
    roomType: 'hangar',
    power: -2,
    description: 'Repairs docked fighters',
    effects: { fighterRepairRate: 1 },
  },
  'fighter-rack': {
    id: 'fighter-rack',
    name: 'Fighter Rack',
    roomType: 'hangar',
    power: 0,
    description: '+2 fighter capacity',
    effects: { fighterCapacity: 2 },
  },
  'pilot-ready-room': {
    id: 'pilot-ready-room',
    name: 'Pilot Ready Room',
    roomType: 'hangar',
    power: -1,
    description: '-25% scramble time',
    effects: { scrambleTimeBonus: 0.25 },
  },

  // Sensor systems
  'basic-sensors': {
    id: 'basic-sensors',
    name: 'Basic Sensors',
    roomType: 'sensors',
    power: -1,
    description: 'Standard detection',
    effects: { sensorRange: 1000 },
    tier: 1,
  },
  'deep-scanner': {
    id: 'deep-scanner',
    name: 'Deep Scanner',
    roomType: 'sensors',
    power: -2,
    description: 'Reveals asteroid contents, anomalies',
    effects: { canDeepScan: true, sensorRange: 500 },
    tier: 2,
  },
  'ecm-suite': {
    id: 'ecm-suite',
    name: 'ECM Suite',
    roomType: 'sensors',
    power: -3,
    description: '-25% enemy accuracy',
    effects: { ecmStrength: 0.25 },
  },
  'targeting-computer': {
    id: 'targeting-computer',
    name: 'Targeting Computer',
    roomType: 'sensors',
    power: -2,
    description: '+15% weapon accuracy',
    effects: { accuracyBonus: 0.15 },
  },

  // Crew quarters systems
  'life-support': {
    id: 'life-support',
    name: 'Life Support',
    roomType: 'crew',
    power: -1,
    description: 'Required for crew survival',
    effects: { canSupportCrew: true },
    required: true,
  },
  'recreation-unit': {
    id: 'recreation-unit',
    name: 'Recreation Unit',
    roomType: 'crew',
    power: -1,
    description: '+10% crew morale',
    effects: { moraleBonus: 0.1 },
  },
  'mess-hall': {
    id: 'mess-hall',
    name: 'Mess Hall',
    roomType: 'crew',
    power: -1,
    description: '-10% food consumption',
    effects: { foodEfficiency: 0.1 },
  },

  // Cargo systems
  'cargo-crane': {
    id: 'cargo-crane',
    name: 'Cargo Crane',
    roomType: 'cargo',
    power: -1,
    description: 'Faster loading/unloading',
    effects: { loadSpeed: 2.0 },
  },
  'refrigeration': {
    id: 'refrigeration',
    name: 'Refrigeration Unit',
    roomType: 'cargo',
    power: -2,
    description: 'Can store perishables',
    effects: { canStorePerishable: true },
  },
  'hazmat-containment': {
    id: 'hazmat-containment',
    name: 'Hazmat Containment',
    roomType: 'cargo',
    power: -1,
    description: 'Can store hazardous materials',
    effects: { canStoreHazmat: true },
  },

  // Research systems
  'research-terminal': {
    id: 'research-terminal',
    name: 'Research Terminal',
    roomType: 'research',
    power: -2,
    description: 'Base research speed',
    effects: { researchRate: 1.0 },
    tier: 1,
  },
  'prototype-fab': {
    id: 'prototype-fab',
    name: 'Prototype Fab',
    roomType: 'research',
    power: -3,
    description: 'Can build experimental items',
    effects: { canPrototype: true },
    tier: 2,
  },
  'data-archive': {
    id: 'data-archive',
    name: 'Data Archive',
    roomType: 'research',
    power: -1,
    description: '+25% research from artifacts',
    effects: { artifactBonus: 0.25 },
  },
};

// ============================================
// HULL TEMPLATES
// ============================================

export const HULL_TEMPLATES = {
  scout: {
    id: 'scout',
    name: 'Scout Frame',
    description: 'Small, fast exploration vessel',
    tier: 1,
    cells: [
      [0,0],[1,0],[2,0],[3,0],[4,0],
      [0,1],[1,1],[2,1],[3,1],[4,1],[5,1],
      [0,2],[1,2],[2,2],[3,2],[4,2],[5,2],[6,2],
      [1,3],[2,3],[3,3],[4,3],[5,3],[6,3],
      [2,4],[3,4],[4,4],[5,4],
      [3,5],[4,5],
    ],
  },
  shuttle: {
    id: 'shuttle',
    name: 'Shuttle Frame',
    description: 'Compact utility vessel',
    tier: 1,
    cells: [
      [1,0],[2,0],[3,0],
      [0,1],[1,1],[2,1],[3,1],[4,1],
      [0,2],[1,2],[2,2],[3,2],[4,2],
      [0,3],[1,3],[2,3],[3,3],[4,3],
      [1,4],[2,4],[3,4],
      [2,5],
    ],
  },
  freighter: {
    id: 'freighter',
    name: 'Freighter Frame',
    description: 'Large cargo capacity',
    tier: 2,
    cells: [
      [2,0],[3,0],[4,0],[5,0],
      [1,1],[2,1],[3,1],[4,1],[5,1],[6,1],
      [0,2],[1,2],[2,2],[3,2],[4,2],[5,2],[6,2],[7,2],
      [0,3],[1,3],[2,3],[3,3],[4,3],[5,3],[6,3],[7,3],
      [0,4],[1,4],[2,4],[3,4],[4,4],[5,4],[6,4],[7,4],
      [0,5],[1,5],[2,5],[3,5],[4,5],[5,5],[6,5],[7,5],
      [1,6],[2,6],[3,6],[4,6],[5,6],[6,6],
      [2,7],[3,7],[4,7],[5,7],
    ],
  },
  frigate: {
    id: 'frigate',
    name: 'Frigate Frame',
    description: 'Balanced combat vessel',
    tier: 2,
    cells: [
      [3,0],[4,0],
      [2,1],[3,1],[4,1],[5,1],
      [1,2],[2,2],[3,2],[4,2],[5,2],[6,2],
      [0,3],[1,3],[2,3],[3,3],[4,3],[5,3],[6,3],[7,3],
      [0,4],[1,4],[2,4],[3,4],[4,4],[5,4],[6,4],[7,4],
      [0,5],[1,5],[2,5],[3,5],[4,5],[5,5],[6,5],[7,5],
      [1,6],[2,6],[3,6],[4,6],[5,6],[6,6],
      [1,7],[2,7],[5,7],[6,7],
      [1,8],[2,8],[5,8],[6,8],
    ],
  },
  cruiser: {
    id: 'cruiser',
    name: 'Cruiser Frame',
    description: 'Large multi-role warship',
    tier: 3,
    cells: [
      [4,0],[5,0],
      [3,1],[4,1],[5,1],[6,1],
      [2,2],[3,2],[4,2],[5,2],[6,2],[7,2],
      [1,3],[2,3],[3,3],[4,3],[5,3],[6,3],[7,3],[8,3],
      [0,4],[1,4],[2,4],[3,4],[4,4],[5,4],[6,4],[7,4],[8,4],[9,4],
      [0,5],[1,5],[2,5],[3,5],[4,5],[5,5],[6,5],[7,5],[8,5],[9,5],
      [0,6],[1,6],[2,6],[3,6],[4,6],[5,6],[6,6],[7,6],[8,6],[9,6],
      [0,7],[1,7],[2,7],[3,7],[4,7],[5,7],[6,7],[7,7],[8,7],[9,7],
      [1,8],[2,8],[3,8],[4,8],[5,8],[6,8],[7,8],[8,8],
      [2,9],[3,9],[4,9],[5,9],[6,9],[7,9],
      [2,10],[3,10],[6,10],[7,10],
      [2,11],[3,11],[6,11],[7,11],
    ],
  },
  carrier: {
    id: 'carrier',
    name: 'Carrier Frame',
    description: 'Massive fighter deployment platform',
    tier: 4,
    cells: [
      [5,0],[6,0],
      [4,1],[5,1],[6,1],[7,1],
      [3,2],[4,2],[5,2],[6,2],[7,2],[8,2],
      [2,3],[3,3],[4,3],[5,3],[6,3],[7,3],[8,3],[9,3],
      [1,4],[2,4],[3,4],[4,4],[5,4],[6,4],[7,4],[8,4],[9,4],[10,4],
      [0,5],[1,5],[2,5],[3,5],[4,5],[5,5],[6,5],[7,5],[8,5],[9,5],[10,5],[11,5],
      [0,6],[1,6],[2,6],[3,6],[4,6],[5,6],[6,6],[7,6],[8,6],[9,6],[10,6],[11,6],
      [0,7],[1,7],[2,7],[3,7],[4,7],[5,7],[6,7],[7,7],[8,7],[9,7],[10,7],[11,7],
      [0,8],[1,8],[2,8],[3,8],[4,8],[5,8],[6,8],[7,8],[8,8],[9,8],[10,8],[11,8],
      [0,9],[1,9],[2,9],[3,9],[4,9],[5,9],[6,9],[7,9],[8,9],[9,9],[10,9],[11,9],
      [1,10],[2,10],[3,10],[4,10],[5,10],[6,10],[7,10],[8,10],[9,10],[10,10],
      [2,11],[3,11],[4,11],[5,11],[6,11],[7,11],[8,11],[9,11],
      [3,12],[4,12],[7,12],[8,12],
      [3,13],[4,13],[7,13],[8,13],
    ],
  },
};

// ============================================
// RESOURCES
// ============================================

export const RESOURCES = {
  credits: { id: 'credits', name: 'Credits', icon: '💰', color: '#fbbf24' },
  metals: { id: 'metals', name: 'Metals', icon: '🔩', color: '#94a3b8' },
  crystals: { id: 'crystals', name: 'Crystals', icon: '💎', color: '#c084fc' },
  gases: { id: 'gases', name: 'Gases', icon: '💨', color: '#67e8f9' },
  rareEarth: { id: 'rareEarth', name: 'Rare Earth', icon: '🌟', color: '#fcd34d' },
  fuel: { id: 'fuel', name: 'Fuel', icon: '⛽', color: '#f97316' },
  food: { id: 'food', name: 'Food', icon: '🍎', color: '#4ade80' },
  electronics: { id: 'electronics', name: 'Electronics', icon: '🔌', color: '#60a5fa' },
  components: { id: 'components', name: 'Components', icon: '⚙️', color: '#a78bfa' },
};

// ============================================
// CREW ROLES
// ============================================

export const CREW_ROLES = {
  pilot: {
    id: 'pilot',
    name: 'Pilot',
    primaryStation: 'cockpit',
    bonus: { maneuverability: 0.1 },
  },
  engineer: {
    id: 'engineer',
    name: 'Engineer',
    primaryStation: 'engine',
    bonus: { efficiency: 0.15, repairRate: 0.2 },
  },
  gunner: {
    id: 'gunner',
    name: 'Gunner',
    primaryStation: 'weapons',
    bonus: { accuracy: 0.15, reloadSpeed: 0.1 },
  },
  medic: {
    id: 'medic',
    name: 'Medic',
    primaryStation: 'medbay',
    bonus: { healRate: 0.5 },
  },
  miner: {
    id: 'miner',
    name: 'Miner',
    primaryStation: 'mining',
    bonus: { extractionRate: 0.25 },
  },
  scientist: {
    id: 'scientist',
    name: 'Scientist',
    primaryStation: 'research',
    bonus: { researchSpeed: 0.2 },
  },
  deckChief: {
    id: 'deckChief',
    name: 'Deck Chief',
    primaryStation: 'hangar',
    bonus: { fighterEffectiveness: 0.25 },
  },
};
